/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.io.File;
import java.io.FileWriter;
import java.io.FileReader;
import java.util.Scanner;
import Principal.Ingreso;
import Principal.Tiempo;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.spi.DirStateFactory.Result;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rober
 */
public class Materiales extends javax.swing.JFrame
{

    DefaultTableModel modelo;
    DefaultTableModel modelo3;
    /**
     * Creates new form Materiales
     */
    ArrayList<Ingreso> lista = new ArrayList<Ingreso>();
    ArrayList<Ingreso> lista2 = new ArrayList<Ingreso>();
    ArrayList<Ingreso> lista3 = new ArrayList<Ingreso>();

    DefaultTableModel jTablaMateriales;
    DefaultTableModel jTablaTiempo;

    int filas;

    public Materiales()
    {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Elementos/Logo2.jpg")));
        model = (DefaultTableModel) this.jTableMateriales.getModel();
        modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Existencias");
        modelo.addColumn("Tamanio cm");
        modelo.addColumn("Marca");
        modelo.addColumn("Precio");
        modelo.addColumn("Color");
        modelo.addColumn("Código de barras");
        modelo.addColumn("Unidades vendidas");
        jTableMateriales.setModel(modelo);

        //Abrir formulario 2
        Registros tabla = new Registros();
        tabla.setVisible(true);

    }

    DefaultTableModel model;

    public void nuevaTabla()
    {
        //Al pasar los datos, limpiamos la primera tabla
        modelo = new DefaultTableModel();
        jTableMateriales.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BtnGuardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnacer = new javax.swing.JButton();
        btnre = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtTamanioCM = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtCodigoDeBarras = new javax.swing.JTextField();
        txtExcistencias = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMateriales = new javax.swing.JTable();
        BtnEditar = new javax.swing.JToggleButton();
        jLabel13 = new javax.swing.JLabel();
        txtUnidades = new javax.swing.JTextField();
        BtnEliminar = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        txtIng = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtSemana = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtTotales = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableTiempo = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtse = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuUsuario = new javax.swing.JMenu();

        jList1.setModel(new javax.swing.AbstractListModel<String>()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Roboto Thin", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¿Comenzamos?");

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 60)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DARWARE");

        BtnGuardar.setBackground(new java.awt.Color(0, 102, 102));
        BtnGuardar.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        BtnGuardar.setText("Guardar");
        BtnGuardar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                BtnGuardarMouseClicked(evt);
            }
        });
        BtnGuardar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BtnGuardarActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ingrese la cantidad de materiales...");

        btnacer.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        btnacer.setText("Acerca de...");
        btnacer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnacerActionPerformed(evt);
            }
        });

        btnre.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        btnre.setText("Regresar");
        btnre.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnreActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jLabel3.setText("Nombre del producto");

        jLabel6.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jLabel6.setText("Número de existencias");

        jLabel7.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jLabel7.setText("Tamaño en cm");

        jLabel8.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jLabel8.setText("Marca");

        jLabel9.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jLabel9.setText("Precio");

        jLabel10.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jLabel10.setText("Color");

        jLabel11.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jLabel11.setText("Código de barras");

        txtNombre.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtNombreActionPerformed(evt);
            }
        });

        btnCrear.setBackground(new java.awt.Color(0, 204, 204));
        btnCrear.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        btnCrear.setText("Crear archivo");
        btnCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        btnCrear.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCrearActionPerformed(evt);
            }
        });

        jTableMateriales.setBackground(new java.awt.Color(204, 255, 255));
        jTableMateriales.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableMateriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String []
            {
                "Nombre del producto", "Numero de excistencias", "Tamaño en Cm", "Marca", "Precio", "Color", "Código de Barras", "Unidades vendidas"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jTableMateriales.setRowHeight(20);
        jTableMateriales.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTableMaterialesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableMateriales);
        if (jTableMateriales.getColumnModel().getColumnCount() > 0)
        {
            jTableMateriales.getColumnModel().getColumn(0).setResizable(false);
            jTableMateriales.getColumnModel().getColumn(1).setResizable(false);
            jTableMateriales.getColumnModel().getColumn(2).setResizable(false);
            jTableMateriales.getColumnModel().getColumn(3).setResizable(false);
            jTableMateriales.getColumnModel().getColumn(4).setResizable(false);
            jTableMateriales.getColumnModel().getColumn(5).setResizable(false);
            jTableMateriales.getColumnModel().getColumn(6).setResizable(false);
            jTableMateriales.getColumnModel().getColumn(7).setResizable(false);
        }

        BtnEditar.setBackground(new java.awt.Color(204, 255, 255));
        BtnEditar.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        BtnEditar.setText("Editar materiales locales");
        BtnEditar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BtnEditarActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jLabel13.setText("Numero de unidades vendidas");

        BtnEliminar.setBackground(new java.awt.Color(255, 51, 51));
        BtnEliminar.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        BtnEliminar.setSelected(true);
        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BtnEliminarActionPerformed(evt);
            }
        });

        jToggleButton1.setBackground(new java.awt.Color(153, 255, 153));
        jToggleButton1.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        jToggleButton1.setText("Calcular Ganancias");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jLabel2.setText("Ingreso por venta");

        txtIng.setEditable(false);
        txtIng.setBackground(new java.awt.Color(204, 255, 204));
        txtIng.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtIngActionPerformed(evt);
            }
        });

        jLabel15.setText("Fecha:");
        jLabel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel16.setText("Hora:");
        jLabel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtSemana.setBackground(new java.awt.Color(102, 255, 255));
        txtSemana.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtSemana.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtSemanaActionPerformed(evt);
            }
        });

        txtHora.setBackground(new java.awt.Color(153, 255, 255));
        txtHora.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel17.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jLabel17.setText("Unidades restantes");

        txtTotales.setEditable(false);
        txtTotales.setBackground(new java.awt.Color(153, 255, 255));

        jTableTiempo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String []
            {
                "Semana", "Hora"
            }
        ));
        jScrollPane4.setViewportView(jTableTiempo);

        jButton1.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        jButton1.setText("Archivos");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        jButton2.setText("Agregar contenido");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        jButton3.setText("Agregar fila");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });

        txtse.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel14.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel14.setText("Ingreso semanal:");

        jButton4.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        jButton4.setText("Registros");
        jButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Limpiar");
        jButton5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSemana)
                            .addComponent(txtHora, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(453, 453, 453)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(95, 95, 95))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(145, 145, 145)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIng)
                                    .addComponent(txtNombre)
                                    .addComponent(txtTamanioCM)
                                    .addComponent(txtMarca)
                                    .addComponent(txtPrecio)
                                    .addComponent(txtColor)
                                    .addComponent(txtCodigoDeBarras)
                                    .addComponent(txtExcistencias, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                                    .addComponent(txtUnidades)
                                    .addComponent(txtTotales))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(318, 318, 318))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnre, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnacer))
                                .addGap(195, 195, 195))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(txtse, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(73, 73, 73))))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnGuardar)
                .addGap(18, 18, 18)
                .addComponent(BtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addGap(25, 25, 25))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(745, 745, 745)
                        .addComponent(jButton5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnacer))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtExcistencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTamanioCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtCodigoDeBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtse, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txtUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(txtTotales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtIng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButton1)
                        .addComponent(btnCrear)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnEditar)
                        .addComponent(BtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)))
                    .addComponent(BtnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/B.jpg"))); // NOI18N
        jMenuUsuario.setText("Materiales");
        jMenuBar1.add(jMenuUsuario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnreActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnreActionPerformed
    {//GEN-HEADEREND:event_btnreActionPerformed
        Principal a = new Principal();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnreActionPerformed

    private void btnacerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnacerActionPerformed
    {//GEN-HEADEREND:event_btnacerActionPerformed
        Dudas2 a = new Dudas2();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnacerActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtNombreActionPerformed
    {//GEN-HEADEREND:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCrearActionPerformed
    {//GEN-HEADEREND:event_btnCrearActionPerformed
        try
        {
            FileWriter fichero = new FileWriter("C:\\Users\\rober\\OneDrive\\Escritorio\\Materiales.txt");
            for (int i = 0; i < lista.size(); i++)
            {
                fichero.write("----------Darware----------" + "\n");
                fichero.write("Semana: " + lista3.get(i).getSemana() + " , " + "Hora: " + lista3.get(i).getHora() + "\n");
                fichero.write("Nombre del producto: " + lista.get(i).getNombre() + "\n");
                fichero.write("Numero de excistencias: " + lista.get(i).getExistencias() + "\n");
                fichero.write("Tamanio del producto: " + lista.get(i).getTamanioCM() + "\n");
                fichero.write("Marca del producto: " + lista.get(i).getMarca() + "\n");
                fichero.write("Precio:  $" + lista.get(i).getPrecio() + "\n");
                fichero.write("Color del producto: " + lista.get(i).getColor() + "\n");
                fichero.write("Codigo de barras: " + lista.get(i).getCodigoDeBarras() + "\n");
                fichero.write("Unidades vendidas: " + lista.get(i).getUnidades() + "\n");
                fichero.write("Unidades restantes: " + txtTotales.getText() + "\n");
                fichero.write("-----------------------------\n");

            }
            for (int i = 0; i < lista.size(); i++)
            {
                if (lista.size() < 0)
                {
                    fichero.write("-----------------------------\n");
                    fichero.write("No disponible" + "\n");
                }
                fichero.write("-----------------------------\n");
                fichero.write("Total semanal: " + lista2.get(i).getIngresos() + "\n");
                fichero.write("-----------------------------\n");
            }
            fichero.close();
        } catch (IOException ex)
        {

            Logger.getLogger(Materiales.class.getName()).log(Level.SEVERE, null, ex);
        }
        try
        {

            FileWriter ingresos = new FileWriter("C:\\Users\\rober\\OneDrive\\Escritorio\\Ingresos por porducto.txt");
            for (int i = 0; i < lista.size(); i++)
            {
                ingresos.write("----------Darware----------" + "\n");
                ingresos.write("Producto: " + lista.get(i).getNombre() + "\n");
                ingresos.write("Unidades vendidas: " + lista.get(i).getUnidades() + "\n");
                ingresos.write("Unidades restantes: " + txtTotales.getText() + "\n");
                ingresos.write("Ganancias por producto: " + txtTotales.getText() + "\n");
                ingresos.write("----------Darware----------" + "\n");
            }
            for (int i = 0; i < lista.size(); i++)
            {
                ingresos.write("----------Darware----------" + "\n");
                ingresos.write("Total semanal: " + lista2.get(i).getIngresos() + "\n");

            }
            ingresos.close();
        } catch (Exception e)
        {

        }
    }//GEN-LAST:event_btnCrearActionPerformed


    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed

        try
        {
            model.addRow(new Object[]
            {
                "", ""
            });
            Ingreso Material = new Ingreso(txtNombre.getText(), txtExcistencias.getText(), txtTamanioCM.getText(), txtMarca.getText(), txtPrecio.getText(), txtColor.getText(), txtCodigoDeBarras.getText(), txtUnidades.getText(), txtIng.getText());
            Ingreso Ingresos = new Ingreso(txtPrecio.getText(), txtUnidades.getText(), txtIng.getText(), txtTotales.getText());
            Ingreso Tiempo = new Ingreso(txtSemana.getText(), txtHora.getText());

            lista.add(Material);
            lista2.add(Ingresos);
            lista3.add(Tiempo);
            mostrar();
//            Unit();
            calcular();
            tiempo();
            limpiar();

        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "No ha escrito nada");
            JOptionPane.showMessageDialog(null, "Puede que el valor que inserto no sea compatible");
            

            clearTxtField();
            Limpia();
            limpiar();

        }


    }//GEN-LAST:event_BtnGuardarActionPerformed

    public void clearTxtField()
    {
        txtSemana.setText(" ");
        txtHora.setText(" ");
        txtNombre.setText(" ");
        txtExcistencias.setText(" ");
        txtTamanioCM.setText(" ");
        txtMarca.setText(" ");
        txtPrecio.setText(" ");
        txtColor.setText(" ");
        txtCodigoDeBarras.setText(" ");
        txtUnidades.setText(" ");
    }

    public void limpiar()
    {
        int c;
            c = jTableMateriales.getSelectedRow();
            lista.remove(c);

        txtSemana.setText(" ");
        txtHora.setText(" ");
        txtNombre.setText(" ");
        txtExcistencias.setText(" ");
        txtTamanioCM.setText(" ");
        txtMarca.setText(" ");
        txtPrecio.setText(" ");
        txtColor.setText(" ");
        txtCodigoDeBarras.setText(" ");
        txtUnidades.setText(" ");
    }

    public void mostrar()
    {
        String matriz[][] = new String[lista.size()][9];

        for (int i = 0; i < lista.size(); i++)
        {
            matriz[i][0] = lista.get(i).getNombre();
            matriz[i][1] = lista.get(i).getExistencias();
            matriz[i][2] = lista.get(i).getTamanioCM();
            matriz[i][3] = lista.get(i).getMarca();
            matriz[i][4] = lista.get(i).getPrecio();
            matriz[i][5] = lista.get(i).getColor();
            matriz[i][6] = lista.get(i).getCodigoDeBarras();
            matriz[i][7] = lista.get(i).getUnidades();
            matriz[i][8] = lista.get(i).getUTotales();
        }

        jTableMateriales.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]
                {
                    "Nombre del producto", "Numero de excistencias", "Tamaño en Cm", "Marca", "Precio", "Color", "Código de Barras", "Unidades vendidas"
                }
        ));

    }

    public void Unit()
    {

    }

    public void calcular()
    {
        //Variables tiempo
        String n3 = txtExcistencias.getText();
        String n4 = txtUnidades.getText();
        //Variables Ingresos
        String n1 = txtPrecio.getText();
        String n2 = txtUnidades.getText();
        //Calculo Ingresos

        float numero1 = Float.parseFloat(n1);
        float numero2 = Float.parseFloat(n2);
        float resultado = numero1 * numero2;
        txtIng.setText(String.valueOf(resultado));
        txtSemana.setText(String.valueOf(resultado));

        //Calculo unidades por día
        float numero3 = Float.parseFloat(n3);
        float numero4 = Float.parseFloat(n4);

        float resultado2 = ((numero3) - (numero4));
        txtTotales.setText(String.valueOf(resultado2));

        float acumulador = 0;
        float total5 = 0;
        for (int i = 0; i < lista2.size(); i++)
        {
            acumulador = acumulador + resultado;
            txtse.setText(String.valueOf(acumulador));
        }

    }

    public void tiempo()
    {
        String matriz3[][] = new String[lista3.size()][2];

        for (int i = 0; i < lista3.size(); i++)
        {
            matriz3[i][0] = lista3.get(i).getSemana();
            matriz3[i][1] = lista3.get(i).getHora();

        }

        jTableTiempo.setModel(new javax.swing.table.DefaultTableModel(
                matriz3,
                new String[]
                {
                    "Semana", "Hora"
                }
        ));

    }

    public void ActuaizarTabala()
    {

    }

    private void BtnGuardarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_BtnGuardarMouseClicked
    {//GEN-HEADEREND:event_BtnGuardarMouseClicked

    }//GEN-LAST:event_BtnGuardarMouseClicked

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnEditarActionPerformed
    {//GEN-HEADEREND:event_BtnEditarActionPerformed
        int c;
        try
        {
            String Nombre, Existencia, Tamanio, Marca, Precio, Color, Codigo, Unidades = null;
            Ingreso aux;
            c = jTableMateriales.getSelectedRow();
            aux = lista.get(c);
            Nombre = (JOptionPane.showInputDialog("Nuevo nombre"));
            aux.setNombre(Nombre);
            Existencia = (JOptionPane.showInputDialog("Nueva cantidad de existencias"));
            aux.setExistencias(Existencia);
            Tamanio = (JOptionPane.showInputDialog("Nuevo Tamaño"));
            aux.setTamanioCM(Tamanio);
            Marca = (JOptionPane.showInputDialog("Nueva Marca"));
            aux.setMarca(Marca);
            Precio = (JOptionPane.showInputDialog("Nuevo Precio"));
            aux.setPrecio(Precio);
            Color = (JOptionPane.showInputDialog("Nuevo Color"));
            aux.setColor(Color);
            Codigo = (JOptionPane.showInputDialog("Nuevo Codigo de barras"));
            aux.setCodigoDeBarras(Codigo);
            Unidades = (JOptionPane.showInputDialog("Nueva cantidad de unidades vendidas"));
            aux.setUnidades(Unidades);

        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Escoger una fila");
        }

        mostrar();


    }//GEN-LAST:event_BtnEditarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnEliminarActionPerformed
    {//GEN-HEADEREND:event_BtnEliminarActionPerformed
        int c;
        try
        {
            c = jTableMateriales.getSelectedRow();
            lista.remove(c);
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Escoja una opción");
        }
        mostrar();
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jToggleButton1ActionPerformed
    {//GEN-HEADEREND:event_jToggleButton1ActionPerformed
        Calculo a = new Calculo();
        a.setVisible(true);
        String info = txtse.getText();
        Calculo.txtSemanal.setText(info);

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void txtSemanaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtSemanaActionPerformed
    {//GEN-HEADEREND:event_txtSemanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSemanaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        GestionArchivos a = new GestionArchivos();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTableMaterialesMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTableMaterialesMouseClicked
    {//GEN-HEADEREND:event_jTableMaterialesMouseClicked
        int seleccion = jTableMateriales.rowAtPoint(evt.getPoint());
        txtNombre.setText(String.valueOf(jTableMateriales.getValueAt(seleccion, 0)));
        txtExcistencias.setText(String.valueOf(jTableMateriales.getValueAt(seleccion, 1)));
        txtTamanioCM.setText(String.valueOf(jTableMateriales.getValueAt(seleccion, 2)));
        txtMarca.setText(String.valueOf(jTableMateriales.getValueAt(seleccion, 3)));
        txtPrecio.setText(String.valueOf(jTableMateriales.getValueAt(seleccion, 4)));
        txtColor.setText(String.valueOf(jTableMateriales.getValueAt(seleccion, 5)));
        txtCodigoDeBarras.setText(String.valueOf(jTableMateriales.getValueAt(seleccion, 6)));
        txtUnidades.setText(String.valueOf(jTableMateriales.getValueAt(seleccion, 7)));

    }//GEN-LAST:event_jTableMaterialesMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        int FilaSeleccionada = jTableMateriales.getSelectedRow();

        if (FilaSeleccionada >= 0)
        {
            String Datos[] = new String[8];
            Datos[0] = jTableMateriales.getValueAt(FilaSeleccionada, 0).toString();
            Datos[1] = jTableMateriales.getValueAt(FilaSeleccionada, 1).toString();
            Datos[2] = jTableMateriales.getValueAt(FilaSeleccionada, 2).toString();
            Datos[3] = jTableMateriales.getValueAt(FilaSeleccionada, 3).toString();
            Datos[4] = jTableMateriales.getValueAt(FilaSeleccionada, 4).toString();
            Datos[5] = jTableMateriales.getValueAt(FilaSeleccionada, 5).toString();
            Datos[6] = jTableMateriales.getValueAt(FilaSeleccionada, 6).toString();
            Datos[7] = jTableMateriales.getValueAt(FilaSeleccionada, 7).toString();

            Registros.modelo2.addRow(Datos);
            modelo.removeRow(FilaSeleccionada);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        for (int i = 0; i < jTableMateriales.getRowCount(); i++)
        {
            String Datos[] = new String[8];
            Datos[0] = jTableMateriales.getValueAt(i, 0).toString();
            Datos[1] = jTableMateriales.getValueAt(i, 1).toString();
            Datos[2] = jTableMateriales.getValueAt(i, 2).toString();
            Datos[3] = jTableMateriales.getValueAt(i, 3).toString();
            Datos[4] = jTableMateriales.getValueAt(i, 4).toString();
            Datos[5] = jTableMateriales.getValueAt(i, 5).toString();
            Datos[6] = jTableMateriales.getValueAt(i, 6).toString();
            Datos[7] = jTableMateriales.getValueAt(i, 7).toString();

            Registros.modelo2.addRow(Datos);
        }
        nuevaTabla();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtIngActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtIngActionPerformed
    {//GEN-HEADEREND:event_txtIngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
        Registros a = new Registros();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton5ActionPerformed
    {//GEN-HEADEREND:event_jButton5ActionPerformed
        Limpia();
        

    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Materiales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtnEditar;
    private javax.swing.JToggleButton BtnEliminar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnacer;
    private javax.swing.JButton btnre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuUsuario;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableMateriales;
    private javax.swing.JTable jTableTiempo;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField txtCodigoDeBarras;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtExcistencias;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtIng;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtSemana;
    private javax.swing.JTextField txtTamanioCM;
    private javax.swing.JTextField txtTotales;
    private javax.swing.JTextField txtUnidades;
    private javax.swing.JLabel txtse;
    // End of variables declaration//GEN-END:variables

    private String getNombre()
    {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private String getExcistencias()
    {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private String getTamanioCM()
    {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private String getMarca()
    {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private String getPrecio()
    {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private String getColor()
    {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private String getCodigoDeBarras()
    {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void Limpia()
    {
        
        int c;
            c = jTableMateriales.getSelectedRow();
            lista.remove(c);
            
        txtSemana.setText(" ");
        txtHora.setText(" ");
        txtNombre.setText(" ");
        txtExcistencias.setText(" ");
        txtTamanioCM.setText(" ");
        txtMarca.setText(" ");
        txtPrecio.setText(" ");
        txtColor.setText(" ");
        txtCodigoDeBarras.setText(" ");
        txtUnidades.setText(" ");
    }
}
